# application.yml
# Location: misfitpoets/misfitpoets-backend/vault-service/src/main/resources/application.yml
server:
  port: 8097  # Ensure this port is unique among your microservices

spring:
  datasource:
    url: jdbc:h2:mem:vaultdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: vault-service
